module.exports={
    model:'淘宝',
    name:'淘宝电商系统',
    menu:[{
        key:'order',
        moduleTyle:'iframe',
        iframeConfig:{
            path:'https://wwww.baidu.com'
        }
    },{
        key:'operating',
        name:'运营活动',
        menuleType:'module',
        moduleTyle:'sider',
        siderConfig:{
            menu:[{
                key:'common',
                name:'优惠券',
                menuType:'module',
                customConfig:{
                    path:'/todo'
                }
            },{
                key:'limited',
                name:'限量购',
                menuType:'module',
                customConfig:{
                    path:'/todo'
                }
            },{
                key:'festival',
                name:'节日活动',
                menuType:'module',
                customConfig:{
                    path:'/todo'
                }
            },
        ] 
        }
        }]
}