module.exports={
    model:'淘宝',
    name:'淘宝',
    desc:'淘宝电商系统',
    homePage:'/todo?proj_key=taobao&key=video',
    menu:[{
        key:'order',
        moduleTyle:'iframe',
        iframeConfig:{
            path:'https://wwww.baidu.com'
        }
    },{
        key:'operating',
        name:'运营活动',
        menuType:'module',
        moduleType:'sider',
        siderConfig:{
            menu:[{
                key:'coupon',
                name:'优惠券',
                menuType:'module',
                customConfig:{
                    path:'/todo'
                }
            },{
                key:'limited',
                name:'限量购',
                menuType:'module',
                customConfig:{
                    path:'/todo'
                }
            },{
                key:'festival',
                name:'节日活动',
                menuType:'module',
                customConfig:{
                    path:'/todo'
                }
            },
        ] 
        }
        }]
}